### PR TITLE
swaylock: Fix crash when unable to connect to sway

### LINKED ISSUE #534: swaylock crashes when XDG_RUNTIME_DIR is not set instead of exiting gracefully.
`$ swaylock`
Output:
```
error: XDG_RUNTIME_DIR not set in the environment.
Error opening display
Error: Signal 11. Printing backtrace
Backtrace: swaylock(error_handler+0xcb) [0x405953]
Backtrace: /lib64/libc.so.6(+0x332f0) [0x7f2adfff52f0]
Backtrace: swaylock(main+0x32a) [0x404af8]
Backtrace: /lib64/libc.so.6(__libc_start_main+0xf0) [0x7f2adffe27b0]
Backtrace: swaylock(_start+0x29) [0x403b39]
Maps:
00400000-0040b000 r-xp 00000000 fe:01 1581475                            /usr/bin/swaylock
0060a000-0060b000 r--p 0000a000 fe:01 1581475                            /usr/bin/swaylock
0060b000-0060c000 rw-p 0000b000 fe:01 1581475                            /usr/bin/swaylock
00e5e000-00e7f000 rw-p 00000000 00:00 0                                  [heap]
7f2ad958c000-7f2ad95a2000 r-xp 00000000 fe:01 1938041                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7f2ad95a2000-7f2ad97a1000 ---p 00016000 fe:01 1938041                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7f2ad97a1000-7f2ad97a2000 r--p 00015000 fe:01 1938041                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7f2ad97a2000-7f2ad97a3000 rw-p 00016000 fe:01 1938041                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1
7f2ad97a3000-7f2ad97ce000 r-xp 00000000 fe:01 1761747                    /usr/lib64/libgraphite2.so.3.0.1
7f2ad97ce000-7f2ad99ce000 ---p 0002b000 fe:01 1761747                    /usr/lib64/libgraphite2.so.3.0.1
7f2ad99ce000-7f2ad99d0000 r--p 0002b000 fe:01 1761747                    /usr/lib64/libgraphite2.so.3.0.1
7f2ad99d0000-7f2ad99d1000 rw-p 0002d000 fe:01 1761747                    /usr/lib64/libgraphite2.so.3.0.1
7f2ad99d1000-7f2ad99e4000 r-xp 00000000 fe:01 1652972                    /lib64/libresolv-2.21.so
7f2ad99e4000-7f2ad9be4000 ---p 00013000 fe:01 1652972                    /lib64/libresolv-2.21.so
7f2ad9be4000-7f2ad9be5000 r--p 00013000 fe:01 1652972                    /lib64/libresolv-2.21.so
7f2ad9be5000-7f2ad9be6000 rw-p 00014000 fe:01 1652972                    /lib64/libresolv-2.21.so
7f2ad9be6000-7f2ad9be8000 rw-p 00000000 00:00 0
7f2ad9be8000-7f2ad9c4c000 r-xp 00000000 fe:01 1764485                    /usr/lib64/libharfbuzz.so.0.10103.0
7f2ad9c4c000-7f2ad9e4c000 ---p 00064000 fe:01 1764485                    /usr/lib64/libharfbuzz.so.0.10103.0
7f2ad9e4c000-7f2ad9e4d000 r--p 00064000 fe:01 1764485                    /usr/lib64/libharfbuzz.so.0.10103.0
7f2ad9e4d000-7f2ad9e4e000 rw-p 00065000 fe:01 1764485                    /usr/lib64/libharfbuzz.so.0.10103.0
7f2ad9e4e000-7f2ad9e53000 r-xp 00000000 fe:01 1741426                    /usr/lib64/libXxf86vm.so.1.0.0
7f2ad9e53000-7f2ada052000 ---p 00005000 fe:01 1741426                    /usr/lib64/libXxf86vm.so.1.0.0
7f2ada052000-7f2ada053000 r--p 00004000 fe:01 1741426                    /usr/lib64/libXxf86vm.so.1.0.0
7f2ada053000-7f2ada054000 rw-p 00005000 fe:01 1741426                    /usr/lib64/libXxf86vm.so.1.0.0
7f2ada054000-7f2ada055000 r-xp 00000000 fe:01 1704975                    /usr/lib64/libxshmfence.so.1.0.0
7f2ada055000-7f2ada255000 ---p 00001000 fe:01 1704975                    /usr/lib64/libxshmfence.so.1.0.0
7f2ada255000-7f2ada256000 r--p 00001000 fe:01 1704975                    /usr/lib64/libxshmfence.so.1.0.0
7f2ada256000-7f2ada257000 rw-p 00002000 fe:01 1704975                    /usr/lib64/libxshmfence.so.1.0.0
7f2ada257000-7f2ada25c000 r-xp 00000000 fe:01 1899100                    /usr/lib64/libxcb-sync.so.1.0.0
7f2ada25c000-7f2ada45c000 ---p 00005000 fe:01 1899100                    /usr/lib64/libxcb-sync.so.1.0.0
7f2ada45c000-7f2ada45d000 r--p 00005000 fe:01 1899100                    /usr/lib64/libxcb-sync.so.1.0.0
7f2ada45d000-7f2ada45e000 rw-p 00006000 fe:01 1899100                    /usr/lib64/libxcb-sync.so.1.0.0
7f2ada45e000-7f2ada46b000 r-xp 00000000 fe:01 1899087                    /usr/lib64/libxcb-randr.so.0.1.0
7f2ada46b000-7f2ada66a000 ---p 0000d000 fe:01 1899087                    /usr/lib64/libxcb-randr.so.0.1.0
7f2ada66a000-7f2ada66b000 r--p 0000c000 fe:01 1899087                    /usr/lib64/libxcb-randr.so.0.1.0
7f2ada66b000-7f2ada66c000 rw-p 0000d000 fe:01 1899087                    /usr/lib64/libxcb-randr.so.0.1.0
7f2ada66c000-7f2ada66e000 r-xp 00000000 fe:01 1899094                    /usr/lib64/libxcb-present.so.0.0.0
7f2ada66e000-7f2ada86d000 ---p 00002000 fe:01 1899094                    /usr/lib64/libxcb-present.so.0.0.0
7f2ada86d000-7f2ada86e000 r--p 00001000 fe:01 1899094                    /usr/lib64/libxcb-present.so.0.0.0
7f2ada86e000-7f2ada86f000 rw-p 00002000 fe:01 1899094                    /usr/lib64/libxcb-present.so.0.0.0
7f2ada86f000-7f2ada871000 r-xp 00000000 fe:01 1899084                    /usr/lib64/libxcb-dri3.so.0.0.0
7f2ada871000-7f2adaa70000 ---p 00002000 fe:01 1899084                    /usr/lib64/libxcb-dri3.so.0.0.0
7f2adaa70000-7f2adaa71000 r--p 00001000 fe:01 1899084                    /usr/lib64/libxcb-dri3.so.0.0.0
7f2adaa71000-7f2adaa72000 rw-p 00002000 fe:01 1899084                    /usr/lib64/libxcb-dri3.so.0.0.0
7f2adaa72000-7f2adaa89000 r-xp 00000000 fe:01 1899088                    /usr/lib64/libxcb-glx.so.0.0.0
7f2adaa89000-7f2adac89000 ---p 00017000 fe:01 1899088                    /usr/lib64/libxcb-glx.so.0.0.0
7f2adac89000-7f2adac8b000 r--p 00017000 fe:01 1899088                    /usr/lib64/libxcb-glx.so.0.0.0
7f2adac8b000-7f2adac8c000 rw-p 00019000 fe:01 1899088                    /usr/lib64/libxcb-glx.so.0.0.0
7f2adac8c000-7f2adac91000 r-xp 00000000 fe:01 1713474                    /usr/lib64/libXfixes.so.3.1.0
7f2adac91000-7f2adae90000 ---p 00005000 fe:01 1713474                    /usr/lib64/libXfixes.so.3.1.0
7f2adae90000-7f2adae91000 r--p 00004000 fe:01 1713474                    /usr/lib64/libXfixes.so.3.1.0
7f2adae91000-7f2adae92000 rw-p 00005000 fe:01 1713474                    /usr/lib64/libXfixes.so.3.1.0
7f2adae92000-7f2adae94000 r-xp 00000000 fe:01 1707089                    /usr/lib64/libXdamage.so.1.1.0
7f2adae94000-7f2adb093000 ---p 00002000 fe:01 1707089                    /usr/lib64/libXdamage.so.1.1.0
7f2adb093000-7f2adb094000 r--p 00001000 fe:01 1707089                    /usr/lib64/libXdamage.so.1.1.0
7f2adb094000-7f2adb095000 rw-p 00002000 fe:01 1707089                    /usr/lib64/libXdamage.so.1.1.0
7f2adb095000-7f2adb0be000 r-xp 00000000 fe:01 1924985                    /usr/lib64/libglapi.so.0.0.0
7f2adb0be000-7f2adb2bd000 ---p 00029000 fe:01 1924985                    /usr/lib64/libglapi.so.0.0.0
7f2adb2bd000-7f2adb2c1000 r--p 00028000 fe:01 1924985                    /usr/lib64/libglapi.so.0.0.0
7f2adb2c1000-7f2adb2c2000 rw-p 0002c000 fe:01 1924985                    /usr/lib64/libglapi.so.0.0.0
7f2adb2c2000-7f2adb2c3000 rw-p 00000000 00:00 0
7f2adb2c3000-7f2adb2c8000 r-xp 00000000 fe:01 1704938                    /usr/lib64/libXdmcp.so.6.0.0
7f2adb2c8000-7f2adb4c7000 ---p 00005000 fe:01 1704938                    /usr/lib64/libXdmcp.so.6.0.0
7f2adb4c7000-7f2adb4c8000 r--p 00004000 fe:01 1704938                    /usr/lib64/libXdmcp.so.6.0.0
7f2adb4c8000-7f2adb4c9000 rw-p 00005000 fe:01 1704938                    /usr/lib64/libXdmcp.so.6.0.0
7f2adb4c9000-7f2adb4cc000 r-xp 00000000 fe:01 1704879                    /usr/lib64/libXau.so.6.0.0
7f2adb4cc000-7f2adb6cb000 ---p 00003000 fe:01 1704879                    /usr/lib64/libXau.so.6.0.0
7f2adb6cb000-7f2adb6cc000 r--p 00002000 fe:01 1704879                    /usr/lib64/libXau.so.6.0.0
7f2adb6cc000-7f2adb6cd000 rw-p 00003000 fe:01 1704879                    /usr/lib64/libXau.so.6.0.0
7f2adb6cd000-7f2adb6db000 r-xp 00000000 fe:01 1655033                    /usr/lib64/libdrm.so.2.4.0
7f2adb6db000-7f2adb8da000 ---p 0000e000 fe:01 1655033                    /usr/lib64/libdrm.so.2.4.0
7f2adb8da000-7f2adb8db000 r--p 0000d000 fe:01 1655033                    /usr/lib64/libdrm.so.2.4.0
7f2adb8db000-7f2adb8dc000 rw-p 0000e000 fe:01 1655033                    /usr/lib64/libdrm.so.2.4.0
7f2adb8dc000-7f2adb8ec000 r-xp 00000000 fe:01 1765686                    /usr/lib64/libwayland-server.so.0.1.0
7f2adb8ec000-7f2adbaeb000 ---p 00010000 fe:01 1765686                    /usr/lib64/libwayland-server.so.0.1.0
7f2adbaeb000-7f2adbaed000 r--p 0000f000 fe:01 1765686                    /usr/lib64/libwayland-server.so.0.1.0
7f2adbaed000-7f2adbaee000 rw-p 00011000 fe:01 1765686                    /usr/lib64/libwayland-server.so.0.1.0
7f2adbaee000-7f2adbafa000 r-xp 00000000 fe:01 1924915                    /usr/lib64/libgbm.so.1.0.0
7f2adbafa000-7f2adbcfa000 ---p 0000c000 fe:01 1924915                    /usr/lib64/libgbm.so.1.0.0
7f2adbcfa000-7f2adbcfb000 r--p 0000c000 fe:01 1924915                    /usr/lib64/libgbm.so.1.0.0
7f2adbcfb000-7f2adbcfc000 rw-p 0000d000 fe:01 1924915                    /usr/lib64/libgbm.so.1.0.0
7f2adbcfc000-7f2adbcff000 r-xp 00000000 fe:01 1899099                    /usr/lib64/libxcb-shape.so.0.0.0
7f2adbcff000-7f2adbefe000 ---p 00003000 fe:01 1899099                    /usr/lib64/libxcb-shape.so.0.0.0
7f2adbefe000-7f2adbeff000 r--p 00002000 fe:01 1899099                    /usr/lib64/libxcb-shape.so.0.0.0
7f2adbeff000-7f2adbf00000 rw-p 00003000 fe:01 1899099                    /usr/lib64/libxcb-shape.so.0.0.0
7f2adbf00000-7f2adbf06000 r-xp 00000000 fe:01 1899103                    /usr/lib64/libxcb-xfixes.so.0.0.0
7f2adbf06000-7f2adc106000 ---p 00006000 fe:01 1899103                    /usr/lib64/libxcb-xfixes.so.0.0.0
7f2adc106000-7f2adc107000 r--p 00006000 fe:01 1899103                    /usr/lib64/libxcb-xfixes.so.0.0.0
7f2adc107000-7f2adc108000 rw-p 00007000 fe:01 1899103                    /usr/lib64/libxcb-xfixes.so.0.0.0
7f2adc108000-7f2adc10c000 r-xp 00000000 fe:01 1899085                    /usr/lib64/libxcb-dri2.so.0.0.0
7f2adc10c000-7f2adc30b000 ---p 00004000 fe:01 1899085                    /usr/lib64/libxcb-dri2.so.0.0.0
7f2adc30b000-7f2adc30c000 r--p 00003000 fe:01 1899085                    /usr/lib64/libxcb-dri2.so.0.0.0
7f2adc30c000-7f2adc30d000 rw-p 00004000 fe:01 1899085                    /usr/lib64/libxcb-dri2.so.0.0.0
7f2adc30d000-7f2adc30e000 r-xp 00000000 fe:01 1854544                    /usr/lib64/libX11-xcb.so.1.0.0
7f2adc30e000-7f2adc50d000 ---p 00001000 fe:01 1854544                    /usr/lib64/libX11-xcb.so.1.0.0
7f2adc50d000-7f2adc50e000 r--p 00000000 fe:01 1854544                    /usr/lib64/libX11-xcb.so.1.0.0
7f2adc50e000-7f2adc50f000 rw-p 00001000 fe:01 1854544                    /usr/lib64/libX11-xcb.so.1.0.0
7f2adc50f000-7f2adc51e000 r-xp 00000000 fe:01 1921670                    /lib64/libbz2.so.1.0.6
7f2adc51e000-7f2adc71d000 ---p 0000f000 fe:01 1921670                    /lib64/libbz2.so.1.0.6
7f2adc71d000-7f2adc71e000 r--p 0000e000 fe:01 1921670                    /lib64/libbz2.so.1.0.6
7f2adc71e000-7f2adc71f000 rw-p 0000f000 fe:01 1921670                    /lib64/libbz2.so.1.0.6
7f2adc71f000-7f2adc745000 r-xp 00000000 fe:01 26228                      /usr/lib64/libexpat.so.1.6.0
7f2adc745000-7f2adc945000 ---p 00026000 fe:01 26228                      /usr/lib64/libexpat.so.1.6.0
7f2adc945000-7f2adc948000 r--p 00026000 fe:01 26228                      /usr/lib64/libexpat.so.1.6.0
7f2adc948000-7f2adc949000 rw-p 00029000 fe:01 26228                      /usr/lib64/libexpat.so.1.6.0
7f2adc949000-7f2adcac3000 r-xp 00000000 fe:01 1752621                    /usr/lib64/libgio-2.0.so.0.4600.2
7f2adcac3000-7f2adccc3000 ---p 0017a000 fe:01 1752621                    /usr/lib64/libgio-2.0.so.0.4600.2
7f2adccc3000-7f2adccc7000 r--p 0017a000 fe:01 1752621                    /usr/lib64/libgio-2.0.so.0.4600.2
7f2adccc7000-7f2adccca000 rw-p 0017e000 fe:01 1752621                    /usr/lib64/libgio-2.0.so.0.4600.2
7f2adccca000-7f2adcccb000 rw-p 00000000 00:00 0
7f2adcccb000-7f2adccce000 r-xp 00000000 fe:01 1762522                    /usr/lib64/libgmodule-2.0.so.0.4600.2
7f2adccce000-7f2adcecd000 ---p 00003000 fe:01 1762522                    /usr/lib64/libgmodule-2.0.so.0.4600.2
7f2adcecd000-7f2adcece000 r--p 00002000 fe:01 1762522                    /usr/lib64/libgmodule-2.0.so.0.4600.2
7f2adcece000-7f2adcecf000 rw-p 00003000 fe:01 1762522                    /usr/lib64/libgmodule-2.0.so.0.4600.2
7f2adcecf000-7f2add006000 r-xp 00000000 fe:01 1762340                    /usr/lib64/libglib-2.0.so.0.4600.2
7f2add006000-7f2add205000 ---p 00137000 fe:01 1762340                    /usr/lib64/libglib-2.0.so.0.4600.2
7f2add205000-7f2add206000 r--p 00136000 fe:01 1762340                    /usr/lib64/libglib-2.0.so.0.4600.2
7f2add206000-7f2add207000 rw-p 00137000 fe:01 1762340                    /usr/lib64/libglib-2.0.so.0.4600.2
7f2add207000-7f2add208000 rw-p 00000000 00:00 0
7f2add208000-7f2add251000 r-xp 00000000 fe:01 1761938                    /usr/lib64/libpango-1.0.so.0.3800.1
7f2add251000-7f2add450000 ---p 00049000 fe:01 1761938                    /usr/lib64/libpango-1.0.so.0.3800.1
7f2add450000-7f2add452000 r--p 00048000 fe:01 1761938                    /usr/lib64/libpango-1.0.so.0.3800.1
7f2add452000-7f2add453000 rw-p 0004a000 fe:01 1761938                    /usr/lib64/libpango-1.0.so.0.3800.1
7f2add453000-7f2add468000 r-xp 00000000 fe:01 1743309                    /usr/lib64/libpangoft2-1.0.so.0.3800.1
7f2add468000-7f2add667000 ---p 00015000 fe:01 1743309                    /usr/lib64/libpangoft2-1.0.so.0.3800.1
7f2add667000-7f2add668000 r--p 00014000 fe:01 1743309                    /usr/lib64/libpangoft2-1.0.so.0.3800.1
7f2add668000-7f2add669000 rw-p 00015000 fe:01 1743309                    /usr/lib64/libpangoft2-1.0.so.0.3800.1
7f2add669000-7f2add764000 r-xp 00000000 fe:01 1651244                    /lib64/libm-2.21.so
7f2add764000-7f2add963000 ---p 000fb000 fe:01 1651244                    /lib64/libm-2.21.so
7f2add963000-7f2add964000 r--p 000fa000 fe:01 1651244                    /lib64/libm-2.21.so
7f2add964000-7f2add965000 rw-p 000fb000 fe:01 1651244                    /lib64/libm-2.21.so
7f2add965000-7f2add9f9000 r-xp 00000000 fe:01 1924901                    /usr/lib64/libGL.so.1.2.0
7f2add9f9000-7f2addbf8000 ---p 00094000 fe:01 1924901                    /usr/lib64/libGL.so.1.2.0
7f2addbf8000-7f2addbfb000 r--p 00093000 fe:01 1924901                    /usr/lib64/libGL.so.1.2.0
7f2addbfb000-7f2addbfc000 rw-p 00096000 fe:01 1924901                    /usr/lib64/libGL.so.1.2.0
7f2addbfc000-7f2addbfd000 rw-p 00000000 00:00 0
7f2addbfd000-7f2addc12000 r-xp 00000000 fe:01 1702937                    /lib64/libz.so.1.2.8
7f2addc12000-7f2adde11000 ---p 00015000 fe:01 1702937                    /lib64/libz.so.1.2.8
7f2adde11000-7f2adde12000 r--p 00014000 fe:01 1702937                    /lib64/libz.so.1.2.8
7f2adde12000-7f2adde13000 rw-p 00015000 fe:01 1702937                    /lib64/libz.so.1.2.8
7f2adde13000-7f2adde24000 r-xp 00000000 fe:01 1741784                    /usr/lib64/libXext.so.6.4.0
7f2adde24000-7f2ade023000 ---p 00011000 fe:01 1741784                    /usr/lib64/libXext.so.6.4.0
7f2ade023000-7f2ade024000 r--p 00010000 fe:01 1741784                    /usr/lib64/libXext.so.6.4.0
7f2ade024000-7f2ade025000 rw-p 00011000 fe:01 1741784                    /usr/lib64/libXext.so.6.4.0
7f2ade025000-7f2ade160000 r-xp 00000000 fe:01 1854531                    /usr/lib64/libX11.so.6.3.0
7f2ade160000-7f2ade35f000 ---p 0013b000 fe:01 1854531                    /usr/lib64/libX11.so.6.3.0
7f2ade35f000-7f2ade362000 r--p 0013a000 fe:01 1854531                    /usr/lib64/libX11.so.6.3.0
7f2ade362000-7f2ade367000 rw-p 0013d000 fe:01 1854531                    /usr/lib64/libX11.so.6.3.0
7f2ade367000-7f2ade368000 rw-p 00000000 00:00 0
7f2ade368000-7f2ade371000 r-xp 00000000 fe:01 1601719                    /usr/lib64/libXrender.so.1.3.0
7f2ade371000-7f2ade570000 ---p 00009000 fe:01 1601719                    /usr/lib64/libXrender.so.1.3.0
7f2ade570000-7f2ade571000 r--p 00008000 fe:01 1601719                    /usr/lib64/libXrender.so.1.3.0
7f2ade571000-7f2ade572000 rw-p 00009000 fe:01 1601719                    /usr/lib64/libXrender.so.1.3.0
7f2ade572000-7f2ade593000 r-xp 00000000 fe:01 1899086                    /usr/lib64/libxcb.so.1.1.0
7f2ade593000-7f2ade793000 ---p 00021000 fe:01 1899086                    /usr/lib64/libxcb.so.1.1.0
7f2ade793000-7f2ade794000 r--p 00021000 fe:01 1899086                    /usr/lib64/libxcb.so.1.1.0
7f2ade794000-7f2ade795000 rw-p 00022000 fe:01 1899086                    /usr/lib64/libxcb.so.1.1.0
7f2ade795000-7f2ade79e000 r-xp 00000000 fe:01 1899093                    /usr/lib64/libxcb-render.so.0.0.0
7f2ade79e000-7f2ade99d000 ---p 00009000 fe:01 1899093                    /usr/lib64/libxcb-render.so.0.0.0
7f2ade99d000-7f2ade99e000 r--p 00008000 fe:01 1899093                    /usr/lib64/libxcb-render.so.0.0.0
7f2ade99e000-7f2ade99f000 rw-p 00009000 fe:01 1899093                    /usr/lib64/libxcb-render.so.0.0.0
7f2ade99f000-7f2ade9a1000 r-xp 00000000 fe:01 1899096                    /usr/lib64/libxcb-shm.so.0.0.0
7f2ade9a1000-7f2adeba1000 ---p 00002000 fe:01 1899096                    /usr/lib64/libxcb-shm.so.0.0.0
7f2adeba1000-7f2adeba2000 r--p 00002000 fe:01 1899096                    /usr/lib64/libxcb-shm.so.0.0.0
7f2adeba2000-7f2adeba3000 rw-p 00003000 fe:01 1899096                    /usr/lib64/libxcb-shm.so.0.0.0
7f2adeba3000-7f2adebd7000 r-xp 00000000 fe:01 1661442                    /usr/lib64/libpng16.so.16.19.0
7f2adebd7000-7f2adedd6000 ---p 00034000 fe:01 1661442                    /usr/lib64/libpng16.so.16.19.0
7f2adedd6000-7f2adedd7000 r--p 00033000 fe:01 1661442                    /usr/lib64/libpng16.so.16.19.0
7f2adedd7000-7f2adedd8000 rw-p 00034000 fe:01 1661442                    /usr/lib64/libpng16.so.16.19.0
7f2adedd8000-7f2adedda000 r-xp 00000000 fe:01 1652585                    /lib64/libdl-2.21.so
7f2adedda000-7f2adefda000 ---p 00002000 fe:01 1652585                    /lib64/libdl-2.21.so
7f2adefda000-7f2adefdb000 r--p 00002000 fe:01 1652585                    /lib64/libdl-2.21.so
7f2adefdb000-7f2adefdc000 rw-p 00003000 fe:01 1652585                    /lib64/libdl-2.21.so
7f2adefdc000-7f2adf002000 r-xp 00000000 fe:01 1924920                    /usr/lib64/libEGL.so.1.0.0
7f2adf002000-7f2adf202000 ---p 00026000 fe:01 1924920                    /usr/lib64/libEGL.so.1.0.0
7f2adf202000-7f2adf203000 r--p 00026000 fe:01 1924920                    /usr/lib64/libEGL.so.1.0.0
7f2adf203000-7f2adf204000 rw-p 00027000 fe:01 1924920                    /usr/lib64/libEGL.so.1.0.0
7f2adf204000-7f2adf2a9000 r-xp 00000000 fe:01 1807074                    /usr/lib64/libfreetype.so.6.11.4
7f2adf2a9000-7f2adf4a9000 ---p 000a5000 fe:01 1807074                    /usr/lib64/libfreetype.so.6.11.4
7f2adf4a9000-7f2adf4af000 r--p 000a5000 fe:01 1807074                    /usr/lib64/libfreetype.so.6.11.4
7f2adf4af000-7f2adf4b0000 rw-p 000ab000 fe:01 1807074                    /usr/lib64/libfreetype.so.6.11.4
7f2adf4b0000-7f2adf4ec000 r-xp 00000000 fe:01 1972152                    /usr/lib64/libfontconfig.so.1.8.0
7f2adf4ec000-7f2adf6eb000 ---p 0003c000 fe:01 1972152                    /usr/lib64/libfontconfig.so.1.8.0
7f2adf6eb000-7f2adf6ed000 r--p 0003b000 fe:01 1972152                    /usr/lib64/libfontconfig.so.1.8.0
7f2adf6ed000-7f2adf6ee000 rw-p 0003d000 fe:01 1972152                    /usr/lib64/libfontconfig.so.1.8.0
7f2adf6ee000-7f2adf78e000 r-xp 00000000 fe:01 1620857                    /usr/lib64/libpixman-1.so.0.32.8
7f2adf78e000-7f2adf98d000 ---p 000a0000 fe:01 1620857                    /usr/lib64/libpixman-1.so.0.32.8
7f2adf98d000-7f2adf995000 r--p 0009f000 fe:01 1620857                    /usr/lib64/libpixman-1.so.0.32.8
7f2adf995000-7f2adf996000 rw-p 000a7000 fe:01 1620857                    /usr/lib64/libpixman-1.so.0.32.8
7f2adf996000-7f2adf9ad000 r-xp 00000000 fe:01 1652964                    /lib64/libpthread-2.21.so
7f2adf9ad000-7f2adfbac000 ---p 00017000 fe:01 1652964                    /lib64/libpthread-2.21.so
7f2adfbac000-7f2adfbad000 r--p 00016000 fe:01 1652964                    /lib64/libpthread-2.21.so
7f2adfbad000-7f2adfbae000 rw-p 00017000 fe:01 1652964                    /lib64/libpthread-2.21.so
7f2adfbae000-7f2adfbb2000 rw-p 00000000 00:00 0
7f2adfbb2000-7f2adfbb8000 r-xp 00000000 fe:01 1652957                    /lib64/librt-2.21.so
7f2adfbb8000-7f2adfdb8000 ---p 00006000 fe:01 1652957                    /lib64/librt-2.21.so
7f2adfdb8000-7f2adfdb9000 r--p 00006000 fe:01 1652957                    /lib64/librt-2.21.so
7f2adfdb9000-7f2adfdba000 rw-p 00007000 fe:01 1652957                    /lib64/librt-2.21.so
7f2adfdba000-7f2adfdc1000 r-xp 00000000 fe:01 1971304                    /usr/lib64/libffi.so.6.0.1
7f2adfdc1000-7f2adffc0000 ---p 00007000 fe:01 1971304                    /usr/lib64/libffi.so.6.0.1
7f2adffc0000-7f2adffc1000 r--p 00006000 fe:01 1971304                    /usr/lib64/libffi.so.6.0.1
7f2adffc1000-7f2adffc2000 rw-p 00007000 fe:01 1971304                    /usr/lib64/libffi.so.6.0.1
7f2adffc2000-7f2ae0153000 r-xp 00000000 fe:01 1652572                    /lib64/libc-2.21.so
7f2ae0153000-7f2ae0353000 ---p 00191000 fe:01 1652572                    /lib64/libc-2.21.so
7f2ae0353000-7f2ae0357000 r--p 00191000 fe:01 1652572                    /lib64/libc-2.21.so
7f2ae0357000-7f2ae0359000 rw-p 00195000 fe:01 1652572                    /lib64/libc-2.21.so
7f2ae0359000-7f2ae035d000 rw-p 00000000 00:00 0
7f2ae035d000-7f2ae039a000 r-xp 00000000 fe:01 1746006                    /usr/lib64/libxkbcommon.so.0.0.0
7f2ae039a000-7f2ae059a000 ---p 0003d000 fe:01 1746006                    /usr/lib64/libxkbcommon.so.0.0.0
7f2ae059a000-7f2ae059d000 r--p 0003d000 fe:01 1746006                    /usr/lib64/libxkbcommon.so.0.0.0
7f2ae059d000-7f2ae059e000 rw-p 00040000 fe:01 1746006                    /usr/lib64/libxkbcommon.so.0.0.0
7f2ae059e000-7f2ae05bf000 r-xp 00000000 fe:01 1762478                    /usr/lib64/libgdk_pixbuf-2.0.so.0.3200.3
7f2ae05bf000-7f2ae07be000 ---p 00021000 fe:01 1762478                    /usr/lib64/libgdk_pixbuf-2.0.so.0.3200.3
7f2ae07be000-7f2ae07bf000 r--p 00020000 fe:01 1762478                    /usr/lib64/libgdk_pixbuf-2.0.so.0.3200.3
7f2ae07bf000-7f2ae07c0000 rw-p 00021000 fe:01 1762478                    /usr/lib64/libgdk_pixbuf-2.0.so.0.3200.3
7f2ae07c0000-7f2ae07cd000 r-xp 00000000 fe:01 1586538                    /lib64/libpam.so.0.84.1
7f2ae07cd000-7f2ae09cd000 ---p 0000d000 fe:01 1586538                    /lib64/libpam.so.0.84.1
7f2ae09cd000-7f2ae09ce000 r--p 0000d000 fe:01 1586538                    /lib64/libpam.so.0.84.1
7f2ae09ce000-7f2ae09cf000 rw-p 0000e000 fe:01 1586538                    /lib64/libpam.so.0.84.1
7f2ae09cf000-7f2ae0a21000 r-xp 00000000 fe:01 1761890                    /usr/lib64/libgobject-2.0.so.0.4600.2
7f2ae0a21000-7f2ae0c20000 ---p 00052000 fe:01 1761890                    /usr/lib64/libgobject-2.0.so.0.4600.2
7f2ae0c20000-7f2ae0c21000 r--p 00051000 fe:01 1761890                    /usr/lib64/libgobject-2.0.so.0.4600.2
7f2ae0c21000-7f2ae0c22000 rw-p 00052000 fe:01 1761890                    /usr/lib64/libgobject-2.0.so.0.4600.2
7f2ae0c22000-7f2ae0c2e000 r-xp 00000000 fe:01 1743289                    /usr/lib64/libpangocairo-1.0.so.0.3800.1
7f2ae0c2e000-7f2ae0e2d000 ---p 0000c000 fe:01 1743289                    /usr/lib64/libpangocairo-1.0.so.0.3800.1
7f2ae0e2d000-7f2ae0e2e000 r--p 0000b000 fe:01 1743289                    /usr/lib64/libpangocairo-1.0.so.0.3800.1
7f2ae0e2e000-7f2ae0e2f000 rw-p 0000c000 fe:01 1743289                    /usr/lib64/libpangocairo-1.0.so.0.3800.1
7f2ae0e2f000-7f2ae0f55000 r-xp 00000000 fe:01 2046834                    /usr/lib64/libcairo.so.2.11400.2
7f2ae0f55000-7f2ae1155000 ---p 00126000 fe:01 2046834                    /usr/lib64/libcairo.so.2.11400.2
7f2ae1155000-7f2ae1158000 r--p 00126000 fe:01 2046834                    /usr/lib64/libcairo.so.2.11400.2
7f2ae1158000-7f2ae115a000 rw-p 00129000 fe:01 2046834                    /usr/lib64/libcairo.so.2.11400.2
7f2ae115a000-7f2ae115b000 rw-p 00000000 00:00 0
7f2ae115b000-7f2ae115f000 r-xp 00000000 fe:01 1765685                    /usr/lib64/libwayland-cursor.so.0.0.0
7f2ae115f000-7f2ae135e000 ---p 00004000 fe:01 1765685                    /usr/lib64/libwayland-cursor.so.0.0.0
7f2ae135e000-7f2ae135f000 r--p 00003000 fe:01 1765685                    /usr/lib64/libwayland-cursor.so.0.0.0
7f2ae135f000-7f2ae1363000 rw-p 00004000 fe:01 1765685                    /usr/lib64/libwayland-cursor.so.0.0.0
7f2ae1363000-7f2ae136f000 r-xp 00000000 fe:01 1765682                    /usr/lib64/libwayland-client.so.0.3.0
7f2ae136f000-7f2ae156f000 ---p 0000c000 fe:01 1765682                    /usr/lib64/libwayland-client.so.0.3.0
7f2ae156f000-7f2ae1571000 r--p 0000c000 fe:01 1765682                    /usr/lib64/libwayland-client.so.0.3.0
7f2ae1571000-7f2ae1572000 rw-p 0000e000 fe:01 1765682                    /usr/lib64/libwayland-client.so.0.3.0
7f2ae1572000-7f2ae1594000 r-xp 00000000 fe:01 1652999                    /lib64/ld-2.21.so
7f2ae173d000-7f2ae1756000 rw-p 00000000 00:00 0
7f2ae1791000-7f2ae1793000 rw-p 00000000 00:00 0
7f2ae1793000-7f2ae1794000 r--p 00021000 fe:01 1652999                    /lib64/ld-2.21.so
7f2ae1794000-7f2ae1795000 rw-p 00022000 fe:01 1652999                    /lib64/ld-2.21.so
7f2ae1795000-7f2ae1796000 rw-p 00000000 00:00 0
7ffe26ea1000-7ffe26ec2000 rw-p 00000000 00:00 0                          [stack]
7ffe26f8f000-7ffe26f91000 r--p 00000000 00:00 0                          [vvar]
7ffe26f91000-7ffe26f93000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```
Same thing happens, when XDG_RUNTIME_DIR doesn't exist.
`$ XDG_RUNTIME_DIR=~/.xdg swaylock` works, as long as ~/.xdg exists.

### PR DESCRIPTION
**Pull request by mikkeloscar**
Prevent swaylock from crashing when it can't connect to sway for
whatever reason. i.e. XDG_RUNTIME_DIR not set.

Fix #534

### CODE REVIEW

File: swaylock/main.c [hunk 1]
```diff
@@ -292,6 +294,10 @@ int main(int argc, char **argv) {
 	surfaces = create_list();
 	registry = registry_poll();
 
+	if (!registry) {
+		sway_abort("Unable to connect to sway");
```
Comment (SirCmpwn) [inline swaylock/main.c]: In this case it's unable to connect to wayland, not sway. And we should probably default to a directory in /tmp instead of just not working if XDG_RUNTIME_DIR isn't set.

Comment (mikkeloscar) [inline swaylock/main.c]: Yeah, I have called it `wayland compositor` now.

`wl_display_connect` expects `XDG_RUNTIME_DIR` but I guess we could change that. That's a different PR though, right? :)

Comment (SirCmpwn) [inline swaylock/main.c]: Yeah, that's fine for a different PR. Do any Wayland clients work at all in these conditions? Should sway set XDG_RUNTIME_DIR itself if not already set?
