### PR TITLE
Fixes dealing with workspace_layout and related bugs [rfc]

### LINKED ISSUE #901: Crash with workspace_layout tabbed on floating container creation
When there is only one direct child of workspace with setting ```workspace_layout tabbed```, sway crashes if a floating window is created.

The issue is caused in file handlers.c, just below line 401. Conditions are done wrong - there is a missing check for floating view, and a check if a wrapper container already exists. I'd suggest postponing fixing this issue until we get a more detailed clarification about workspace_layout from i3 (that was referenced in PR #793).

### PR DESCRIPTION
**Pull request by thejan2009**
Fix #901. Minimal working example: default config, on empty workspace $mod+w, ```swaymsg exec nautilus```, Ctrl+i. Previously you'd get a segfault, after fixing that the popup would appear, but nautilus would become invisible. That's fixed in the second commit.

### CODE REVIEW

File: sway/commands/layout.c [hunk 1]
```diff
@@ -37,22 +37,22 @@ struct cmd_results *cmd_layout(int argc, char **argv) {
...
-			parent->layout = L_VERT;
+			swayc_change_layout(parent,L_VERT);
 		} else if (strcasecmp(argv[0], "toggle") == 0 && argc == 2 && strcasecmp(argv[1], "split") == 0) {
 			if (parent->layout == L_VERT) {
-				parent->layout = L_HORIZ;
+				swayc_change_layout(parent,L_HORIZ);
 			} else {
-				parent->layout = L_VERT;
+				swayc_change_layout(parent,L_VERT);
 			}
```
Comment (SirCmpwn) [inline sway/commands/layout.c]: style: add spaces after the commas in function calls

**Comment by thejan2009** [comment]
I found a better way to do it. Views under workspaces should now be encapsulated pretty much every time.
